name: Lint GitHub Actions Workflows
on:
  push:
    paths:
    - '.github/workflows/**'

jobs:
  actionlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b # v4.1.4
      - name: "Lint workflow files"
        uses: docker://docker.mirror.hashicorp.services/rhysd/actionlint:latest
        with:
          # Ignore actionlint errors from strict typing for outputs that we use
          # in our e2e tests.
          # This error occurs because vault-action's outputs are dynamic but
          # actionlint expects action.yml to define them.
          args: >
            -ignore "property \"othersecret\" is not defined in object type"
            -ignore "property \"jsonstring\" is not defined in object type"
            -ignore "property \"jsonstringmultiline\" is not defined in object type"
